//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageExplorer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageExplorer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 作者： 的本地化字符串。
        /// </summary>
        public static string Dialog_CreatedByLabel {
            get {
                return ResourceManager.GetString("Dialog_CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依赖项： 的本地化字符串。
        /// </summary>
        public static string Dialog_DependenciesLabel {
            get {
                return ResourceManager.GetString("Dialog_DependenciesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deterministic (dll/exe): 的本地化字符串。
        /// </summary>
        public static string Dialog_DeterministicValidation {
            get {
                return ResourceManager.GetString("Dialog_DeterministicValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开发依赖项： 的本地化字符串。
        /// </summary>
        public static string Dialog_DevelopmentDependencyLabel {
            get {
                return ResourceManager.GetString("Dialog_DevelopmentDependencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载包 {0} {1} 的本地化字符串。
        /// </summary>
        public static string Dialog_DownloadingPackage {
            get {
                return ResourceManager.GetString("Dialog_DownloadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Dialog_Errors {
            get {
                return ResourceManager.GetString("Dialog_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 框架程序集引用： 的本地化字符串。
        /// </summary>
        public static string Dialog_FrameworkAssembliesLabel {
            get {
                return ResourceManager.GetString("Dialog_FrameworkAssembliesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编译器标记： 的本地化字符串。
        /// </summary>
        public static string Dialog_HasCompilerFlags {
            get {
                return ResourceManager.GetString("Dialog_HasCompilerFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 健壮性： 的本地化字符串。
        /// </summary>
        public static string Dialog_Health {
            get {
                return ResourceManager.GetString("Dialog_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包 Id： 的本地化字符串。
        /// </summary>
        public static string Dialog_IdLabel {
            get {
                return ResourceManager.GetString("Dialog_IdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Dialog_Information {
            get {
                return ResourceManager.GetString("Dialog_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包 URL {0} 无效且无法打开。 的本地化字符串。
        /// </summary>
        public static string Dialog_InvalidPackageUrl {
            get {
                return ResourceManager.GetString("Dialog_InvalidPackageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言： 的本地化字符串。
        /// </summary>
        public static string Dialog_LanguageLabel {
            get {
                return ResourceManager.GetString("Dialog_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可证 Meta： 的本地化字符串。
        /// </summary>
        public static string Dialog_LicenceMeta {
            get {
                return ResourceManager.GetString("Dialog_LicenceMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达式： 的本地化字符串。
        /// </summary>
        public static string Dialog_LicenseExpression {
            get {
                return ResourceManager.GetString("Dialog_LicenseExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达式版本： 的本地化字符串。
        /// </summary>
        public static string Dialog_LicenseExpressionVersion {
            get {
                return ResourceManager.GetString("Dialog_LicenseExpressionVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小客户端版本： 的本地化字符串。
        /// </summary>
        public static string Dialog_MinVersionLabel {
            get {
                return ResourceManager.GetString("Dialog_MinVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包信息 的本地化字符串。
        /// </summary>
        public static string Dialog_MoreInfo {
            get {
                return ResourceManager.GetString("Dialog_MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有依赖项 的本地化字符串。
        /// </summary>
        public static string Dialog_NoDependencyLabel {
            get {
                return ResourceManager.GetString("Dialog_NoDependencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有支持的文件|*.nupkg;*.snupkg;*.nuspec|NuGet包文件 (*.nupkg)|*.nupkg|NuGet 符号包文件 (*.snupkg)|*.snupkg|NuSpec 文件 (*.nuspec)|*.nuspec 的本地化字符串。
        /// </summary>
        public static string Dialog_OpenFileFilter {
            get {
                return ResourceManager.GetString("Dialog_OpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有者： 的本地化字符串。
        /// </summary>
        public static string Dialog_OwnersLabel {
            get {
                return ResourceManager.GetString("Dialog_OwnersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布者： 的本地化字符串。
        /// </summary>
        public static string Dialog_PublisherLabel {
            get {
                return ResourceManager.GetString("Dialog_PublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报告滥用 的本地化字符串。
        /// </summary>
        public static string Dialog_ReportAbuse {
            get {
                return ResourceManager.GetString("Dialog_ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支： 的本地化字符串。
        /// </summary>
        public static string Dialog_RepositoryBranch {
            get {
                return ResourceManager.GetString("Dialog_RepositoryBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交： 的本地化字符串。
        /// </summary>
        public static string Dialog_RepositoryCommit {
            get {
                return ResourceManager.GetString("Dialog_RepositoryCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储库： 的本地化字符串。
        /// </summary>
        public static string Dialog_RepositoryLabel {
            get {
                return ResourceManager.GetString("Dialog_RepositoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型： 的本地化字符串。
        /// </summary>
        public static string Dialog_RepositoryType {
            get {
                return ResourceManager.GetString("Dialog_RepositoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url： 的本地化字符串。
        /// </summary>
        public static string Dialog_RepositoryUrl {
            get {
                return ResourceManager.GetString("Dialog_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要求接收许可证： 的本地化字符串。
        /// </summary>
        public static string Dialog_RequireLicenseLabel {
            get {
                return ResourceManager.GetString("Dialog_RequireLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你想保存更改吗？ 的本地化字符串。
        /// </summary>
        public static string Dialog_SaveQuestion {
            get {
                return ResourceManager.GetString("Dialog_SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用的： 的本地化字符串。
        /// </summary>
        public static string Dialog_ServiceableLabel {
            get {
                return ResourceManager.GetString("Dialog_ServiceableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部 Url 希望向 NuGet 包浏览器 添加发布源。
        ///是否要将 &apos;{0}&apos; 添加到包发布源列表中? 的本地化字符串。
        /// </summary>
        public static string Dialog_SetActivePackagePublishSource {
            get {
                return ResourceManager.GetString("Dialog_SetActivePackagePublishSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示详情... 的本地化字符串。
        /// </summary>
        public static string Dialog_ShowDetails {
            get {
                return ResourceManager.GetString("Dialog_ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名： 的本地化字符串。
        /// </summary>
        public static string Dialog_SignatureValidation {
            get {
                return ResourceManager.GetString("Dialog_SignatureValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源链接： 的本地化字符串。
        /// </summary>
        public static string Dialog_SourceLinkValidation {
            get {
                return ResourceManager.GetString("Dialog_SourceLinkValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签： 的本地化字符串。
        /// </summary>
        public static string Dialog_TagLabel {
            get {
                return ResourceManager.GetString("Dialog_TagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NuGet 包浏览器 的本地化字符串。
        /// </summary>
        public static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题： 的本地化字符串。
        /// </summary>
        public static string Dialog_TitleLabel {
            get {
                return ResourceManager.GetString("Dialog_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证结果： 的本地化字符串。
        /// </summary>
        public static string Dialog_ValidationResult {
            get {
                return ResourceManager.GetString("Dialog_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包验证结果： 的本地化字符串。
        /// </summary>
        public static string Dialog_ValidationResultTitle {
            get {
                return ResourceManager.GetString("Dialog_ValidationResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本： 的本地化字符串。
        /// </summary>
        public static string Dialog_VersionLabel {
            get {
                return ResourceManager.GetString("Dialog_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看许可证条款 的本地化字符串。
        /// </summary>
        public static string Dialog_ViewLicense {
            get {
                return ResourceManager.GetString("Dialog_ViewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Dialog_Warnings {
            get {
                return ResourceManager.GetString("Dialog_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to add the file &apos;{0}&apos; to &apos;{1}&apos; folder instead? 的本地化字符串。
        /// </summary>
        public static string MoveContentFileToFolder {
            get {
                return ResourceManager.GetString("MoveContentFileToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NuGet does not do anything special with files at the package root. The extension of this file indicates that it is intended to be placed in the &apos;{0}&apos; folder.  的本地化字符串。
        /// </summary>
        public static string MoveContentFileToFolderExplanation {
            get {
                return ResourceManager.GetString("MoveContentFileToFolderExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (not framework specific) 的本地化字符串。
        /// </summary>
        public static string NoFxDependencyGroup {
            get {
                return ResourceManager.GetString("NoFxDependencyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network connection is not detected. 的本地化字符串。
        /// </summary>
        public static string NoNetworkConnection {
            get {
                return ResourceManager.GetString("NoNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 download 的本地化字符串。
        /// </summary>
        public static string PackageChooser_ActionDownload {
            get {
                return ResourceManager.GetString("PackageChooser_ActionDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hide all versions 的本地化字符串。
        /// </summary>
        public static string PackageChooser_ActionHideAllVersions {
            get {
                return ResourceManager.GetString("PackageChooser_ActionHideAllVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 open 的本地化字符串。
        /// </summary>
        public static string PackageChooser_ActionOpen {
            get {
                return ResourceManager.GetString("PackageChooser_ActionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 show all versions 的本地化字符串。
        /// </summary>
        public static string PackageChooser_ActionShowAllVersions {
            get {
                return ResourceManager.GetString("PackageChooser_ActionShowAllVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alternate Package: 的本地化字符串。
        /// </summary>
        public static string PackageChooser_AlternatePackage {
            get {
                return ResourceManager.GetString("PackageChooser_AlternatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear search 的本地化字符串。
        /// </summary>
        public static string PackageChooser_ClearSearchButtonTooltip {
            get {
                return ResourceManager.GetString("PackageChooser_ClearSearchButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloads 的本地化字符串。
        /// </summary>
        public static string PackageChooser_ColumnHeaderDownloads {
            get {
                return ResourceManager.GetString("PackageChooser_ColumnHeaderDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Published 的本地化字符串。
        /// </summary>
        public static string PackageChooser_ColumnHeaderPublished {
            get {
                return ResourceManager.GetString("PackageChooser_ColumnHeaderPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string PackageChooser_ColumnHeaderVersion {
            get {
                return ResourceManager.GetString("PackageChooser_ColumnHeaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deprecated: 的本地化字符串。
        /// </summary>
        public static string PackageChooser_Deprecated {
            get {
                return ResourceManager.GetString("PackageChooser_Deprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author(s): 的本地化字符串。
        /// </summary>
        public static string PackageChooser_DetailAuthors {
            get {
                return ResourceManager.GetString("PackageChooser_DetailAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date published: 的本地化字符串。
        /// </summary>
        public static string PackageChooser_DetailDatePublished {
            get {
                return ResourceManager.GetString("PackageChooser_DetailDatePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string PackageChooser_DetailDescription {
            get {
                return ResourceManager.GetString("PackageChooser_DetailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License: 的本地化字符串。
        /// </summary>
        public static string PackageChooser_DetailLicense {
            get {
                return ResourceManager.GetString("PackageChooser_DetailLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project URL: 的本地化字符串。
        /// </summary>
        public static string PackageChooser_DetailProjectUrl {
            get {
                return ResourceManager.GetString("PackageChooser_DetailProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report Abuse: 的本地化字符串。
        /// </summary>
        public static string PackageChooser_DetailReportAbuse {
            get {
                return ResourceManager.GetString("PackageChooser_DetailReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags: 的本地化字符串。
        /// </summary>
        public static string PackageChooser_DetailTags {
            get {
                return ResourceManager.GetString("PackageChooser_DetailTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string PackageChooser_DetailVersion {
            get {
                return ResourceManager.GetString("PackageChooser_DetailVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Package source: 的本地化字符串。
        /// </summary>
        public static string PackageChooser_PackageSource {
            get {
                return ResourceManager.GetString("PackageChooser_PackageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string PackageChooser_RefreshButtonTooltip {
            get {
                return ResourceManager.GetString("PackageChooser_RefreshButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search for package 的本地化字符串。
        /// </summary>
        public static string PackageChooser_SearchBoxTooltip {
            get {
                return ResourceManager.GetString("PackageChooser_SearchBoxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search (Ctrl+E) 的本地化字符串。
        /// </summary>
        public static string PackageChooser_SearchBoxWatermark {
            get {
                return ResourceManager.GetString("PackageChooser_SearchBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string PackageChooser_SearchButtonTooltip {
            get {
                return ResourceManager.GetString("PackageChooser_SearchButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show pre-release packages 的本地化字符串。
        /// </summary>
        public static string PackageChooser_ShowPreReleasePackages {
            get {
                return ResourceManager.GetString("PackageChooser_ShowPreReleasePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Package 的本地化字符串。
        /// </summary>
        public static string PackageChooser_WindowTitle {
            get {
                return ResourceManager.GetString("PackageChooser_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to download package correctly. The contents of the package could not be verified. 的本地化字符串。
        /// </summary>
        public static string PackageContentsVerifyError {
            get {
                return ResourceManager.GetString("PackageContentsVerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no contents or dependencies in the package. 的本地化字符串。
        /// </summary>
        public static string PackageHasNoFile {
            get {
                return ResourceManager.GetString("PackageHasNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect to {0} 的本地化字符串。
        /// </summary>
        public static string ProxyConnectToMessage {
            get {
                return ResourceManager.GetString("ProxyConnectToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disallowed 的本地化字符串。
        /// </summary>
        public static string Validation_Disallowed {
            get {
                return ResourceManager.GetString("Validation_Disallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains untracked sources (obj) 的本地化字符串。
        /// </summary>
        public static string Validation_HasUntrackedSources {
            get {
                return ResourceManager.GetString("Validation_HasUntrackedSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Source Link 的本地化字符串。
        /// </summary>
        public static string Validation_InvalidSourceLink {
            get {
                return ResourceManager.GetString("Validation_InvalidSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing 的本地化字符串。
        /// </summary>
        public static string Validation_MissingCompilerFlags {
            get {
                return ResourceManager.GetString("Validation_MissingCompilerFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has Symbols, No Source Link 的本地化字符串。
        /// </summary>
        public static string Validation_MissingSourceLink {
            get {
                return ResourceManager.GetString("Validation_MissingSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing Symbols 的本地化字符串。
        /// </summary>
        public static string Validation_MissingSymbols {
            get {
                return ResourceManager.GetString("Validation_MissingSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non deterministic 的本地化字符串。
        /// </summary>
        public static string Validation_NonDeterministic {
            get {
                return ResourceManager.GetString("Validation_NonDeterministic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No files found to validate 的本地化字符串。
        /// </summary>
        public static string Validation_NothingToValidate {
            get {
                return ResourceManager.GetString("Validation_NothingToValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pending 的本地化字符串。
        /// </summary>
        public static string Validation_Pending {
            get {
                return ResourceManager.GetString("Validation_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Present 的本地化字符串。
        /// </summary>
        public static string Validation_Present {
            get {
                return ResourceManager.GetString("Validation_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suspect 的本地化字符串。
        /// </summary>
        public static string Validation_Suspect {
            get {
                return ResourceManager.GetString("Validation_Suspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Validation_Unknown {
            get {
                return ResourceManager.GetString("Validation_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid 的本地化字符串。
        /// </summary>
        public static string Validation_Valid {
            get {
                return ResourceManager.GetString("Validation_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid with Symbol Server 的本地化字符串。
        /// </summary>
        public static string Validation_ValidExternal {
            get {
                return ResourceManager.GetString("Validation_ValidExternal", resourceCulture);
            }
        }
    }
}
