//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGetPe.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NuGetResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NuGetResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGetPe.NuGetResources", typeof(NuGetResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 不能创建没有依赖关系或内容的包。 的本地化字符串。
        /// </summary>
        internal static string CannotCreateEmptyPackage {
            get {
                return ResourceManager.GetString("CannotCreateEmptyPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依赖项 &apos;{0}&apos; 的版本无效。 的本地化字符串。
        /// </summary>
        internal static string DependencyHasInvalidVersion {
            get {
                return ResourceManager.GetString("DependencyHasInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 已经为 &apos;{1}&apos; 定义了一个依赖项。 的本地化字符串。
        /// </summary>
        internal static string DuplicateDependenciesDefined {
            get {
                return ResourceManager.GetString("DuplicateDependenciesDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 &apos;{0}&apos; 错误。 的本地化字符串。
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 的模式版本与 NuGet 包浏览器 的 &apos;{1}&apos; 版本不兼容。请将NuGet 包浏览器升级到最新版本。 的本地化字符串。
        /// </summary>
        internal static string IncompatibleSchema {
            get {
                return ResourceManager.GetString("IncompatibleSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理请求时出现错误。请验证 &apos;{0}&apos; 是一个有效的来源。 的本地化字符串。
        /// </summary>
        internal static string InvalidFeed {
            get {
                return ResourceManager.GetString("InvalidFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的框架名称格式。预期值 {framework}{version}-{profile}. 的本地化字符串。
        /// </summary>
        internal static string InvalidFrameworkNameFormat {
            get {
                return ResourceManager.GetString("InvalidFrameworkNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包ID &apos;{0}&apos; 包含无效字符。有效的包id示例包括 &apos;MyPackage&apos; and &apos;MyPackage.Sample&apos;。 的本地化字符串。
        /// </summary>
        internal static string InvalidPackageId {
            get {
                return ResourceManager.GetString("InvalidPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 不是有效的版本字符串。 的本地化字符串。
        /// </summary>
        internal static string InvalidVersionString {
            get {
                return ResourceManager.GetString("InvalidVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;dependencies&gt; 元素不能同时包含 &lt;group&gt; 和 &lt;dependency&gt; 子元素。 的本地化字符串。
        /// </summary>
        internal static string Manifest_DependenciesHasMixedElements {
            get {
                return ResourceManager.GetString("Manifest_DependenciesHasMixedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要依赖项 Id。 的本地化字符串。
        /// </summary>
        internal static string Manifest_DependencyIdRequired {
            get {
                return ResourceManager.GetString("Manifest_DependencyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排除路径 &apos;{0}&apos; 包含无效字符。 的本地化字符串。
        /// </summary>
        internal static string Manifest_ExcludeContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("Manifest_ExcludeContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包 Id 不能超过100个字符。 的本地化字符串。
        /// </summary>
        internal static string Manifest_IdMaxLengthExceeded {
            get {
                return ResourceManager.GetString("Manifest_IdMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包清单中的 &apos;minClientVersion&apos; 属性的值无效。它必须是一个有效的版本字符串。 的本地化字符串。
        /// </summary>
        internal static string Manifest_InvalidMinClientVersion {
            get {
                return ResourceManager.GetString("Manifest_InvalidMinClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个包的稳定发行版不应该依赖于预发行包。要么修改依赖项 &apos;{0}&apos; 的版本规范，要么更新版本字段。 的本地化字符串。
        /// </summary>
        internal static string Manifest_InvalidPrereleaseDependency {
            get {
                return ResourceManager.GetString("Manifest_InvalidPrereleaseDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的程序集引用 &apos;{0}&apos;。确保在lib目录中存在名为 &apos;{0}&apos; 的文件。 的本地化字符串。
        /// </summary>
        internal static string Manifest_InvalidReference {
            get {
                return ResourceManager.GetString("Manifest_InvalidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的架构名称空间 &apos;{0}&apos;。 的本地化字符串。
        /// </summary>
        internal static string Manifest_InvalidSchemaNamespace {
            get {
                return ResourceManager.GetString("Manifest_InvalidSchemaNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到与模式版本 &apos;{0}&apos; 对应的名称空间。在 &apos;{1}&apos; 中的VersionToSchemaMappings 字典中添加一个条目。 的本地化字符串。
        /// </summary>
        internal static string Manifest_InvalidVersion {
            get {
                return ResourceManager.GetString("Manifest_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;references&gt; 元素不能同时包含 &lt;group&gt; 和 &lt;reference&gt; 子元素。 的本地化字符串。
        /// </summary>
        internal static string Manifest_ReferencesHasMixedElements {
            get {
                return ResourceManager.GetString("Manifest_ReferencesHasMixedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 package\metadata\references\group 至少必须包含一个 &lt;reference&gt; 子元素。 的本地化字符串。
        /// </summary>
        internal static string Manifest_ReferencesIsEmpty {
            get {
                return ResourceManager.GetString("Manifest_ReferencesIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 是必须的。 的本地化字符串。
        /// </summary>
        internal static string Manifest_RequiredMetadataMissing {
            get {
                return ResourceManager.GetString("Manifest_RequiredMetadataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用要求接受许可证。 的本地化字符串。
        /// </summary>
        internal static string Manifest_RequireLicenseAcceptanceRequiresLicenseUrl {
            get {
                return ResourceManager.GetString("Manifest_RequireLicenseAcceptanceRequiresLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源路径 &apos;{0}&apos; 包含无效字符。 的本地化字符串。
        /// </summary>
        internal static string Manifest_SourceContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("Manifest_SourceContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标路径 &apos;{0}&apos; 包含无效字符。 的本地化字符串。
        /// </summary>
        internal static string Manifest_TargetContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("Manifest_TargetContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能为空。 的本地化字符串。
        /// </summary>
        internal static string Manifest_UriCannotBeEmpty {
            get {
                return ResourceManager.GetString("Manifest_UriCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺失框架名称。 的本地化字符串。
        /// </summary>
        internal static string MissingFrameworkName {
            get {
                return ResourceManager.GetString("MissingFrameworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没找到文件： &apos;{0}&apos;。 的本地化字符串。
        /// </summary>
        internal static string PackageAuthoring_FileNotFound {
            get {
                return ResourceManager.GetString("PackageAuthoring_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法正确下载包。包内容无法验证。 的本地化字符串。
        /// </summary>
        internal static string PackageContentsVerifyError {
            get {
                return ResourceManager.GetString("PackageContentsVerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包不包含清单。 的本地化字符串。
        /// </summary>
        internal static string PackageDoesNotContainManifest {
            get {
                return ResourceManager.GetString("PackageDoesNotContainManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接到源 &apos;{0}&apos; 需要安装 Windows Identity Foundation 运行时。 的本地化字符串。
        /// </summary>
        internal static string UnableToLocateWIF {
            get {
                return ResourceManager.GetString("UnableToLocateWIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法解析 &apos;{0}&apos;。 的本地化字符串。
        /// </summary>
        internal static string UnableToResolveUri {
            get {
                return ResourceManager.GetString("UnableToResolveUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知模式版本 &apos;{0}&apos;。 的本地化字符串。
        /// </summary>
        internal static string UnknownSchemaVersion {
            get {
                return ResourceManager.GetString("UnknownSchemaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密钥 &apos;{0}&apos; 不存在。 的本地化字符串。
        /// </summary>
        internal static string UserSettings_KeyDoesNotExist {
            get {
                return ResourceManager.GetString("UserSettings_KeyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 部分不存在。 的本地化字符串。
        /// </summary>
        internal static string UserSettings_SectionDoesNotExist {
            get {
                return ResourceManager.GetString("UserSettings_SectionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法解析配置文件。 的本地化字符串。
        /// </summary>
        internal static string UserSettings_UnableToParseConfigFile {
            get {
                return ResourceManager.GetString("UserSettings_UnableToParseConfigFile", resourceCulture);
            }
        }
    }
}
