//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageExplorerViewModel {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageExplorerViewModel.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证书 的本地化字符串。
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证书信息 的本地化字符串。
        /// </summary>
        public static string CertificateInfo {
            get {
                return ResourceManager.GetString("CertificateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证书存储区 的本地化字符串。
        /// </summary>
        public static string CertificateStore {
            get {
                return ResourceManager.GetString("CertificateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供用于对包进行签名的代码签名证书。 的本地化字符串。
        /// </summary>
        public static string ChooseCertificate_Description {
            get {
                return ResourceManager.GetString("ChooseCertificate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择用于包签名的证书 的本地化字符串。
        /// </summary>
        public static string ChooseCertificate_Title {
            get {
                return ResourceManager.GetString("ChooseCertificate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要删除 &apos;{0}&apos; 吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmToDeleteContent {
            get {
                return ResourceManager.GetString("ConfirmToDeleteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已删除的文件或文件夹不可恢复。 的本地化字符串。
        /// </summary>
        public static string ConfirmToDeleteContent_Title {
            get {
                return ResourceManager.GetString("ConfirmToDeleteContent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要删除这个扩展吗？ 的本地化字符串。
        /// </summary>
        public static string ConfirmToDeletePlugin {
            get {
                return ResourceManager.GetString("ConfirmToDeletePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要替换现有文件 &apos;{0}&apos; ？ 的本地化字符串。
        /// </summary>
        public static string ConfirmToReplaceExsitingFile {
            get {
                return ResourceManager.GetString("ConfirmToReplaceExsitingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此文件夹中已经有一个同名的文件。 的本地化字符串。
        /// </summary>
        public static string ConfirmToReplaceExsitingFile_Title {
            get {
                return ResourceManager.GetString("ConfirmToReplaceExsitingFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要替换磁盘上现有的文件 &apos;{0}&apos; ？ 的本地化字符串。
        /// </summary>
        public static string ConfirmToReplaceFile {
            get {
                return ResourceManager.GetString("ConfirmToReplaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在这个位置已经有一个同名的文件。 的本地化字符串。
        /// </summary>
        public static string ConfirmToReplaceFile_Title {
            get {
                return ResourceManager.GetString("ConfirmToReplaceFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在连接到包源… 的本地化字符串。
        /// </summary>
        public static string ConnectingMessage {
            get {
                return ResourceManager.GetString("ConnectingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要保存你所做的更改吗？ 的本地化字符串。
        /// </summary>
        public static string Dialog_SaveQuestion {
            get {
                return ResourceManager.GetString("Dialog_SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NuGet 包浏览器 的本地化字符串。
        /// </summary>
        public static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作无法完成，因为编辑表单有一些无效的输入。 的本地化字符串。
        /// </summary>
        public static string EditFormHasInvalidInput {
            get {
                return ResourceManager.GetString("EditFormHasInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此包已经成功导出。 的本地化字符串。
        /// </summary>
        public static string ExportPackageSuccess {
            get {
                return ResourceManager.GetString("ExportPackageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新文件与另一个文件夹具有相同的名称。 的本地化字符串。
        /// </summary>
        public static string FileNameConflictWithExistingDirectory {
            get {
                return ResourceManager.GetString("FileNameConflictWithExistingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 哈希算法名称 的本地化字符串。
        /// </summary>
        public static string HashAlgorithName {
            get {
                return ResourceManager.GetString("HashAlgorithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载... 的本地化字符串。
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检测到网络连接。 的本地化字符串。
        /// </summary>
        public static string NoNetworkConnection {
            get {
                return ResourceManager.GetString("NoNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开此文件可能会潜在地损害您的计算机。你想继续吗？ 的本地化字符串。
        /// </summary>
        public static string OpenExecutableScriptWarning {
            get {
                return ResourceManager.GetString("OpenExecutableScriptWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 &apos;{0}&apos; 是可执行的。 的本地化字符串。
        /// </summary>
        public static string OpenExecutableScriptWarning_Title {
            get {
                return ResourceManager.GetString("OpenExecutableScriptWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包生成失败，由于此错误： 的本地化字符串。
        /// </summary>
        public static string PackageCreationFailed {
            get {
                return ResourceManager.GetString("PackageCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不正确 的本地化字符串。
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要密码 的本地化字符串。
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 &apos;{0}&apos; 被重命名或从其物理位置删除。现在将从包中删除它。 的本地化字符串。
        /// </summary>
        public static string PhysicalFileMissing {
            get {
                return ResourceManager.GetString("PhysicalFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *** 注册读取此文件类型的插件无法读取此文件的内容。 *** 的本地化字符串。
        /// </summary>
        public static string PluginFailToReadContent {
            get {
                return ResourceManager.GetString("PluginFailToReadContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还有另一个与 &apos;{0}&apos; 同名的文件或文件夹。 的本地化字符串。
        /// </summary>
        public static string RenameCausesNameCollison {
            get {
                return ResourceManager.GetString("RenameCausesNameCollison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择证书 的本地化字符串。
        /// </summary>
        public static string SelectCertificate {
            get {
                return ResourceManager.GetString("SelectCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名 的本地化字符串。
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在对包进行签名... 的本地化字符串。
        /// </summary>
        public static string SigningPackage {
            get {
                return ResourceManager.GetString("SigningPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除签名并重新对包进行签名... 的本地化字符串。
        /// </summary>
        public static string SigningPackageAndRemoveSignature {
            get {
                return ResourceManager.GetString("SigningPackageAndRemoveSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签名包 的本地化字符串。
        /// </summary>
        public static string SignPackage {
            get {
                return ResourceManager.GetString("SignPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间戳服务器 的本地化字符串。
        /// </summary>
        public static string TimestampServer {
            get {
                return ResourceManager.GetString("TimestampServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *** 不支持此文件的格式。 *** 的本地化字符串。
        /// </summary>
        public static string UnsupportedFormatMessage {
            get {
                return ResourceManager.GetString("UnsupportedFormatMessage", resourceCulture);
            }
        }
    }
}
